//===- air_host_impl.h -----------------------------------------*- C++ -*-===//
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef AIR_HOST_IMPL_H
#define AIR_HOST_IMPL_H

#include <stddef.h>

// AIE config functions generated by AIE dialect lowering
struct air_rt_aie_functions_t {
  size_t (*get_pdi)(void **);
  size_t (*get_insts)(void **);
};

/*
        Get the name of the device driver

        Use this to device to map various device memory regions into the host
   address space
*/
const char *air_get_driver_name(void);

#endif
